[package]
name = "rustlations"
version = "0.1.0"
authors = ["sayden <mariocaster@gmail.com>"]

[dependencies]
lazy_static = "0.2"
redis = "0.8.0"
serde = "1.0.10"
serde_derive = "1.0"
serde_json = "1.0.2"